/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderSummary = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'total' : IDL.Float64,
  'discount' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'availableColors' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const CartItem = IDL.Record({
  'color' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'calculateOrderSummary' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [OrderSummary],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderSummary = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'total' : IDL.Float64,
    'discount' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'availableColors' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CartItem = IDL.Record({
    'color' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'calculateOrderSummary' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [OrderSummary],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Float64)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };